In [36]:
import os

# Concatenate text files to create a corpus of Russell’s writings
meragefiledir = os.getcwd()+'/corpus'
filenames = os.listdir(meragefiledir)
f = open('corpus.txt','w')

for file in filenames:  
    filepath = meragefiledir+'/'+file
    for line in open(filepath):
        line = line.strip()
        f.writelines(line)
f.close()

In [37]:
import collections
with open('corpus.txt','r',encoding='utf-8') as f:
    sequence = f.read()
c_dict = collections.Counter(sequence)
# print(c_dict)
chara_num = len(c_dict)

In [38]:
import numpy as np
rand_list = np.random.random_sample((chara_num,))
new_dict = dict(zip(c_dict.keys(), rand_list))
print(new_dict)

{'L': 0.4595642712050536, 'E': 0.40152224035719286, 'C': 0.3531215849100996, 'T': 0.12807467406584705, 'U': 0.6840980825066243, 'R': 0.44389725986958994, ' ': 0.14050157811534425, 'I': 0.38873318348609665, 'N': 0.5682992521762926, 'D': 0.46666321271840816, 'S': 0.01821274710163856, 'P': 0.2889389003495424, 'h': 0.25517340577235414, 'i': 0.11969930288957975, 'l': 0.09424987291012799, 'o': 0.6261361154205785, 's': 0.05957109677799177, 'p': 0.3306379118349283, 'y': 0.7759468673125288, ',': 0.02813659927087675, 'f': 0.3412908437279376, 'r': 0.0052285421991598025, 'm': 0.8513711452844243, 't': 0.6007350401168765, 'e': 0.37651125907273875, 'a': 0.39379961044493905, 'd': 0.35012645812569954, 'g': 0.8809486649144623, 'c': 0.8351768513208411, 'n': 0.7881791935496637, 'v': 0.782601513726547, 'w': 0.5321377082954493, 'u': 0.6929800185318469, 'b': 0.5301564486444602, '.': 0.2551268608860393, '-': 0.33085657332672824, ';': 0.5326724201249082, 'q': 0.3459834999306757, 'A': 0.15993834043637456, 'x': 

In [39]:
chara_range = list(range(0, chara_num))
index_dict = dict(zip(c_dict.keys(), chara_range))
print(index_dict)

{'L': 0, 'E': 1, 'C': 2, 'T': 3, 'U': 4, 'R': 5, ' ': 6, 'I': 7, 'N': 8, 'D': 9, 'S': 10, 'P': 11, 'h': 12, 'i': 13, 'l': 14, 'o': 15, 's': 16, 'p': 17, 'y': 18, ',': 19, 'f': 20, 'r': 21, 'm': 22, 't': 23, 'e': 24, 'a': 25, 'd': 26, 'g': 27, 'c': 28, 'n': 29, 'v': 30, 'w': 31, 'u': 32, 'b': 33, '.': 34, '-': 35, ';': 36, 'q': 37, 'A': 38, 'x': 39, 'k': 40, 'K': 41, 'H': 42, 'W': 43, 'J': 44, 'M': 45, 'B': 46, '"': 47, 'G': 48, ':': 49, 'F': 50, 'ï': 51, '_': 52, "'": 53, 'O': 54, 'j': 55, '?': 56, '[': 57, '4': 58, ']': 59, '\xa0': 60, '3': 61, '2': 62, 'â': 63, 'æ': 64, 'z': 65, '5': 66, 'Y': 67, '1': 68, '(': 69, ')': 70, '6': 71, '8': 72, '7': 73, '9': 74, '§': 75, '0': 76, 'V': 77, 'X': 78, '!': 79, 'α': 80, 'β': 81, 'γ': 82, 'é': 83, 'Z': 84, '/': 85, 'Q': 86, '|': 87, '>': 88, 'τ': 89, 'ὸ': 90, 'π': 91, 'ό': 92, 'σ': 93, 'ο': 94, 'ν': 95, 'η': 96, 'λ': 97, 'ί': 98, 'κ': 99, 'ὴ': 100, 'φ': 101, 'ι': 102, 'ρ': 103, 'ή': 104, '=': 105, 'è': 106, 'ë': 107, 'ü': 108, 'É': 109, '′': 1

Extracting inputs and outputs to LSTM

In [40]:
window = 100
i = 0
X = []
Y = []
while(i < (len(sequence)-window)):
    in_tmp_list=[]
    out_tmp_array = np.zeros((chara_num,), dtype=int)
    inp = sequence[i : (i+window-1)]
    outp = sequence[i+window-1]
    for j in inp:
        in_tmp_list.append(new_dict[j])
    out_tmp_array[index_dict[outp]] += 1
    X.append(in_tmp_list)
    Y.append(out_tmp_array)
    i += 1

In [41]:
# X is the inputs to LSTM, Y is the outputs
X = np.array(X)
Y = np.array(Y)
print(X)
print(Y)

[[0.45956427 0.40152224 0.35312158 ... 0.37651126 0.78260151 0.37651126]
 [0.40152224 0.35312158 0.12807467 ... 0.78260151 0.37651126 0.35012646]
 [0.35312158 0.12807467 0.68409808 ... 0.37651126 0.35012646 0.14050158]
 ...
 [0.14050158 0.00522854 0.37651126 ... 0.60073504 0.14050158 0.88094866]
 [0.00522854 0.37651126 0.78817919 ... 0.14050158 0.88094866 0.62613612]
 [0.37651126 0.78817919 0.35012646 ... 0.88094866 0.62613612 0.62613612]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [46]:
X = X.reshape(1044062, 99, 1)

In [47]:
from keras.models import Sequential
from keras.layers import Dense, Activation, LSTM
from keras.callbacks import ModelCheckpoint
import h5py
# build LSTM model
model=Sequential()
model.add(LSTM(units=400, input_shape=(X.shape[1], X.shape[2]), dropout=0.2))
model.add(Dense(chara_num))
model.add(Activation('softmax'))
# compile: loss, optimizer, metrics
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# define the checkpoint
filepath='weights-improvement-{epoch:02d}-{loss:.4f}.hdf5'
checkpoint = ModelCheckpoint(filepath, monitor='loss', verbose=1, save_best_only=True, mode='min')
callbacks_list = [checkpoint]
model.fit(X, Y, epochs=20, batch_size=1000, callbacks=callbacks_list)
print(model.summary())
# loss, accuracy = model.evaluate(X, Y)
# print("\nLoss: %.2f, Accuracy: %.2f%%" % (loss, accuracy*100))

Epoch 1/20
1044062/1044062 [==============================] - 730s 699us/step - loss: 2.7341 - acc: 0.2562

Epoch 00001: loss improved from inf to 2.73405, saving model to weights-improvement-01-2.7341.hdf5
Epoch 2/20
1044062/1044062 [==============================] - 648s 621us/step - loss: 2.7110 - acc: 0.2591

Epoch 00002: loss improved from 2.73405 to 2.71095, saving model to weights-improvement-02-2.7110.hdf5
Epoch 3/20
1044062/1044062 [==============================] - 649s 621us/step - loss: 2.7100 - acc: 0.2591

Epoch 00003: loss improved from 2.71095 to 2.71001, saving model to weights-improvement-03-2.7100.hdf5
Epoch 4/20
1044062/1044062 [==============================] - 645s 618us/step - loss: 2.7092 - acc: 0.2591

Epoch 00004: loss improved from 2.71001 to 2.70923, saving model to weights-improvement-04-2.7092.hdf5
Epoch 5/20
1044062/1044062 [==============================] - 657s 629us/step - loss: 2.7085 - acc: 0.2591

Epoch 00005: loss improved from 2.70923 to 2.70853, 

In [48]:
# load the network weights
filename = 'weights-improvement-20-2.7052.hdf5'
model.load_weights(filename)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [128]:
# generate characters
int_to_char=dict(zip(index_dict.values(),index_dict.keys()))
dataX = 'There are those who take mental phenomena naively, just as they would physical phenomena. This school of psychologists tends not to emphasize the object.'
pattern = dataX[0:99]
test_data=[]
for x in pattern:
    test_data.append([index_dict[x]])
test_data=np.array(test_data)
test_data=test_data.reshape(1,99,1)
for i in range(1000):
    X=test_data[0][i:]
    X=X.reshape(1,X.shape[0],1)
    prediction = model.predict(X, verbose=0)
    index = np.argmax(prediction)
#     result = int_to_char[index]
    test_data = test_data.reshape(99+i,1)
    test_data=np.vstack((test_data, [index]))
    test_data = test_data.reshape(1,test_data.shape[0],1)

In [133]:
gen=''
for x in test_data[0]:
    gen=gen+int_to_char[x[0]]
print(pattern, gen)

There are those who take mental phenomena naively, just as they would physical phenomena. This schole ondyrose that the  on  of thesenises of the penaril sore te the contrady the pone al te be seal thans  of the pase of the onte that of the one andethed,ef enes to the corter of and the past of a  of erestr bot ve cases this is there os a  and there ar  of a  one cins in this peried the  ef the pense derire to the pase and thating to things which is core not to this,ether, thin whateis the pans of senind the pensende  ats and to fon  oth rone  fet re song not benser tratil  ondtinct, the  one os cencar  ase tho gerief  of this is the pan  andwhe onter an  and that the  one of eur pense detarns tiuld that the  are on  of the pase of the pan  of this werl is the pase on the condtituet and the pases on tise ofasper to the sase of tiuss ar  ot ic not bontention of this,indtire  and the  arter the pensesing and the ober to the pase ofether which ale serertirle the cord  ant al inrerencent of